
trigger:
- main

pool:
  name: MyAgentPool

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
  displayName: 'Install .NET SDK'

- script: |
    dotnet restore --interactive 
    dotnet build --configuration Release
    dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Restore, Build and Pack NuGet Package'

- script: |
    echo "Checking for packaged NuGet files..."
    dir $(Build.ArtifactStagingDirectory)  # List files for debugging
  displayName: 'Debug - Check NuGet Package Path'

- script: |
    dotnet nuget push "$(Build.ArtifactStagingDirectory)/*.nupkg" --source "StringExtensionsFeed" --api-key az --skip-duplicate
  displayName: 'Push to Azure Artifacts Feed'
